### ISSUE TITLE
How to set up the app? Flutter run isn't working

### ISSUE THREAD

**Issue by leogmg** [dgewe/Tinder-App-Flutter#1]
Hi Fredrik! First of all, I am a great fan, cheers from Brazil! 🇧🇷

Frederik, even when usem FVM to try to flutter run on version < 1.22.4 the project doesn't seem to work
Is there anyway in which you could explain to us how to run the project starting from git clone? 

Thanks for your patience and GREAT WORK!!! keep going!!

**Comment by dgewe** [comment]
Hello, please try with Flutter SDK Version 1.22.4 for now, it should work.
I will probably make an update in the future to work with other versions.

Steps that works for me with sdk version 1.22.4:

1. Clone project
2. Open project with android studio
3. Replace google-services with a real one from firebase
4. Press "get dependencies" (should be a bar in the top), it's also
possible to run using command
5. Run project (green play button)

If this doesn't work, please provide me with more details about what errors
you get.

I can help you more later today, currently at work.

// Fredrik


Den fre 11 juni 2021 kl 14:48 skrev Leonardo Gomes ***@***.***

**Comment by leogmg** [comment]
Hey Fredrik! Your step by step was awesome, and it's working smoothly now!
I hope you had a great day at work, and thanks a lot! 
Wish you the best 👋

**Comment by whitelegs** [comment]
Just wanted to say that I am your biggest fan, cheers from Sweden!
Please continue sharing more apps. 💯👍

**Comment by hessio** [comment]
Hi I don't seem to have the green play button at the top?
