### ISSUE TITLE
Unable to get project to work

### ISSUE THREAD

**Issue by hessio** [dgewe/Tinder-App-Flutter#2]
Hi I followed all the steps you recommended in the other issues to try to be able to run this project in android studio, unfortunately I have not been able to. I have a windows 10 PC, I have also tried on my macbook and my Ubuntu 20.4 machine and none seem to be able to do this

**Comment by dgewe** [comment]
Hello!

Using Flutter SDK version 1.22.4 with the steps that I provided in the other issue should be working.
Please make sure that you are using the correct Flutter SDK and that you've also done "get dependencies".

I could also recommend that if you're using IntelliJ IDEA, then maybe clearing the cache could help.

Clear cache: Go to File (top left corner) -> Invalidate Caches -> Invalidate and Restart

Then you could also try rebuilding the project.

If you still don't have a play button available as you mentioned in the other issue thread, then maybe check the run configuration if you find some solution there.

**Comment by dgewe** [comment]
I assume that you got it working, if not then please open another issue. 
The repo is now also updated to work with Flutter 2.x.
