### ISSUE TITLE
Possible null pointer exception

### ISSUE THREAD

**Issue by hessio** [dgewe/Tinder-App-Flutter#3]
Hi there I was looking at this source code and my understanding is that in this line the code will try to execute 

`(e as FirebaseException).message` but if this equates to `null` it will execute `e.toString()` which will give a null pointer exception am I interpreting this wrong?

Thanks 

https://github.com/dgewe/Tinder-App-Flutter/blob/a3fbe564fa94b5160258deef9b749b8febd18424/lib/data/db/remote/firebase_auth_source.dart#L14

**Comment by krabinowitz1** [comment]
@hessio If `(e as FirebaseException).message` is null then it means e is not of type FirebaseException, but it is still an Exception which means it will implement toString(), so a null pointer exception should not occur.

**Comment by hessio** [comment]
Ah cool I see thanks for clearing that up for me :)
