### ISSUE TITLE
Execution failed : malformed JSON at line 1 column 10 path $

### ISSUE THREAD

**Issue by RajuNarula369** [dgewe/Tinder-App-Flutter#6]
Execution failed for task ':app:processDebugGoogleServices'.
> com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10 path $

**Comment by dgewe** [comment]
Replacing the **google-services.json** file with one from Firebase will solve your issue.

Please see the setup guide in the README file for further details.
